export const actionTypes = {
    SET_COUNTRY: "SET_COUNTRY",
    SET_DATA_COUNTRY: "SET_DATA_COUNTRY",
    SET_DATA_SEASON: "SET_DATA_SEASON",
    SET_SEASON: "SET_SEASON",
    SET_LEAGUE: "SET_LEAGUE",
    SET_LEAGUE_SELECT: "SET_LEAGUE_SELECT",
    SET_LEAGUE_SELECT_OPTION: "SET_LEAGUE_SELECT_OPTION",
    SET_TEAM_NAME: "SET_TEAM_NAME",
    SET_PLAYERS: "SET_PLAYERS",
    SET_FORMATION: "SET_FORMATION",
    SET_TEAM_NAME_LABEL: "SET_TEAM_NAME_LABEL",
    SET_TEAM_LOGO: "SET_TEAM_LOGO",
};
